name: fitness_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.67.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/App_Logo.jpg
    - assets/images/health_icon.jpg
    - assets/images/steps_icon.jpg
    - assets/images/workout_icon.jpg

flutter_native_splash:
  color: "#33373A"
  image: assets/images/App_Logo.png
  android: true
  ios: true

  android_12:
    color: "#33373A"  # دعم أندرويد 12+
    image: assets/images/App_Logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/App_Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/App_Logo.png"
