name: fitness_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.67.0
  sensors_plus: ^6.1.1
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.1
  permission_handler: ^11.0.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  device_preview: ^1.2.0
  modal_progress_hud_nsn: ^0.5.1
  pinput: ^5.0.1
  cloud_firestore: ^5.6.6
  animated_toggle_switch: ^0.8.4
  provider: ^6.0.0
  syncfusion_flutter_gauges: ^29.1.33
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_sliders: ^29.1.33
  syncfusion_flutter_core: ^29.1.33
  syncfusion_flutter_charts: ^29.1.33
  equatable: ^2.0.7
  awesome_circular_chart: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  file: ^7.0.1
  firebase_storage: ^12.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/App_Logo.jpg
    - assets/images/health_icon.jpg
    - assets/images/steps_icon.jpg
    - assets/images/workout_icon.jpg
    - assets/images/runner.jpg
    - assets/images/shose.png
    - assets/images/profile.jpg
    - assets/images/user_icon.jpg
fonts:
  - family: NotoSans
    fonts:
      - asset: fonts/NotoSans-Regular.ttf

flutter_native_splash:
  color: "#33373A"
  image: assets/images/App_Logo.png
  android: true
  ios: true

  android_12:
    color: "#33373A"
    image: assets/images/App_Logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/App_Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/App_Logo.png"
