// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjiF9WARBOJGYz4WmYivfHUhGFEg2ftuc',
    appId: '1:32283517265:web:f26089151aeb401aea7370',
    messagingSenderId: '32283517265',
    projectId: 'fitness-4f2fb',
    authDomain: 'fitness-4f2fb.firebaseapp.com',
    storageBucket: 'fitness-4f2fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2WyNiD9ShH5Ss3g6_coH_Vsgboq-OAI',
    appId: '1:32283517265:android:d8f4e857cbc18a1cea7370',
    messagingSenderId: '32283517265',
    projectId: 'fitness-4f2fb',
    storageBucket: 'fitness-4f2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45un1CeJeFzwNu5YZtNu3ay6A9_ETjF0',
    appId: '1:32283517265:ios:142c17f2efc831c2ea7370',
    messagingSenderId: '32283517265',
    projectId: 'fitness-4f2fb',
    storageBucket: 'fitness-4f2fb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45un1CeJeFzwNu5YZtNu3ay6A9_ETjF0',
    appId: '1:32283517265:ios:142c17f2efc831c2ea7370',
    messagingSenderId: '32283517265',
    projectId: 'fitness-4f2fb',
    storageBucket: 'fitness-4f2fb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjiF9WARBOJGYz4WmYivfHUhGFEg2ftuc',
    appId: '1:32283517265:web:e1ace7c716250d21ea7370',
    messagingSenderId: '32283517265',
    projectId: 'fitness-4f2fb',
    authDomain: 'fitness-4f2fb.firebaseapp.com',
    storageBucket: 'fitness-4f2fb.firebasestorage.app',
  );
}